### ISSUE TITLE
Error seeding database

### ISSUE THREAD

**Issue by trezy** [Ariel-Thomas/adventurers-league-log#130]
Hey @Ariel-Thomas, I'm having trouble getting the database to seed. When I run `bundle exec phil_columns seed`, I'm getting an error about `AddAdventureFormInputs::AdventureFormInput` being an uninitialized constant. It looks like the only place `AdventureFormInput` is being used is in the seed files. Any idea what's going on here?

Here's the full error I'm getting:

```
Loading environment: config/phil_columns ...
Seeding up to version all
Executing seed: 20150425050533_add_adventure_form_inputs ... ERROR
bundler: failed to load command: phil_columns (/usr/local/bundle/bin/phil_columns)
NameError: uninitialized constant AddAdventureFormInputs::AdventureFormInput
  db/seeds/20150425050533_add_adventure_form_inputs.rb:28:in `block in up'
  db/seeds/20150425050533_add_adventure_form_inputs.rb:27:in `each'
  db/seeds/20150425050533_add_adventure_form_inputs.rb:27:in `up'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/seeder.rb:19:in `block (2 levels) in execute'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/output.rb:30:in `confirm'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/seeder.rb:13:in `block in execute'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/seeder.rb:12:in `each'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/seeder.rb:12:in `execute'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/command/seed.rb:13:in `execute'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/cli.rb:162:in `execute'
  /usr/local/bundle/gems/phil_columns-0.5.0/lib/phil_columns/cli.rb:156:in `seed'
  /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /usr/local/bundle/gems/phil_columns-0.5.0/bin/phil_columns:6:in `<top (required)>'
  /usr/local/bundle/bin/phil_columns:17:in `load'
  /usr/local/bundle/bin/phil_columns:17:in `<top (required)>'
```

**Comment by Ariel-Thomas** [comment]
Ack, yeah, a lot of my seeds are more outdated than I realized.

**Comment by Ariel-Thomas** [comment]
Okay, should be fixed.

**Comment by trezy** [comment]
Haha, no worries! I pulled your changes into my fork and all seems to be working well. Cheers! 🍻
